---
- name: Create an azure instance
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  vars:
    location: westus
    resource_group: Resource_Group_Tower
    vm_size: 
    vm_name: linuxvm001
    offer: CentOS
    publisher: 
    admin_password: RedP@ssw0rd!

  tasks:

  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
      tags:
          ansible_provisioned: Tower1
          delete: never
     
  #- name: remove account, if it exists
  #  azure_rm_storageaccount:
  #    resource_group: "{{ resource_group }}"
  #    name: "{{ vm_name }}"
  #    state: absent

  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      account_type: Standard_LRS

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: testvn001
      address_prefixes: "10.10.0.0/16"
  
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: subnet001
      address_prefix: "10.10.0.0/24"
      virtual_network: testvn001
  
  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ vm_name }}"
  
  - name: Create security group that allows SSH and HTTPS
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
        - name: HTTPS
          protocol: Tcp
          destination_port_range: 443
          access: Allow
          priority: 102
          direction: Inbound
  
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      virtual_network: testvn001
      subnet: subnet001
      public_ip_name: "{{ vm_name }}"
      security_group: "{{ vm_name }}"
  
  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: "{{ vm_size }}" #Standard_D1
      storage_account: "{{ vm_name }}"
      storage_container: "{{ vm_name }}"
      storage_blob: "{{ vm_name }}.vhd"
      admin_username: devops
      admin_password: "{{ admin_password }}"
      network_interfaces: "{{ vm_name }}"
      image:
        offer: "{{ offer }}"
        publisher: "{{ publisher }}"
        sku: '7.7'
        version: latest
